config/routes.rb
Rails.application.routes.draw do

  resources :bank_accounts, path: '/'

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base
  validates :bank_account_name, presence: true
  validates :bank_account_owner, presence: true
  validates :bank_account_type_code, presence: true
  validates :financial_insitution_number, presence: true
  validates :branch_transit_number, presence: true
  validates :account_number, presence: true

  def api_properties
    self.attributes.except(* %w(id updated_at created_at)).symbolize_keys
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  def create
    @bank_account = BankAccount.new(bank_account_params)
    if @bank_account.save
      redirect_to @bank_account, notice: 'Bank account was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bank_accounts/1
  def update
    if bank_account_params[:add_bank_account] == 'true'
      peloton  = Pelokit::BankAccount.new @bank_account.api_properties
      response = peloton.add
      if peloton.success  # Save the generated bank account ID.
        @bank_account.bank_account_id = response[:bank_account_id]
        @bank_account.save!
      end
      redirect_to @bank_account, notice: JSON.pretty_generate(response)

    elsif bank_account_params[:deposit_funds] == 'true'
      peloton = Pelokit::ElectronicFundsTransfer.new bank_account_id: @bank_account.bank_account_id,
                                                     amount:          bank_account_params[:amount],
                                                     transfer_date:   Date.tomorrow.iso8601
      response = peloton.deposit
      redirect_to @bank_account, notice: JSON.pretty_generate(response)

    elsif bank_account_params[:delete_bank_account] == 'true'

      peloton  = Pelokit::BankAccount.new bank_account_id: @bank_account.bank_account_id
      response = peloton.remove
      response = response.marshal_dump if response.is_a? OpenStruct
      redirect_to @bank_account, notice: JSON.pretty_generate(response)

    elsif @bank_account.update(bank_account_params)
      # Handle a regular PUT.
      redirect_to @bank_account, notice: 'Bank account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bank_accounts/1
  def destroy
    @bank_account.destroy
    redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bank_account_params
      params.require(:bank_account).permit(:bank_account_id, :bank_account_name, :bank_account_owner, :bank_account_type_code, :financial_insitution_number, :branch_transit_number, :account_number, :add_bank_account, :deposit_funds, :amount, :delete_bank_account)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bank_accounts/_form.html.slim
= form_for @bank_account do |f|
  - if @bank_account.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bank_account.errors.count, "error")} prohibited this bank_account from being saved:"
      ul
        - @bank_account.errors.full_messages.each do |message|
          li = message

  .row
    .three.columns
      = f.label :friendly_name
      = f.text_field :bank_account_name
    .three.columns
      = f.label :bank_account_owner
      = f.text_field :bank_account_owner
    .three.columns
      = f.label 'type code (0=chq, 1=sav)'
      = f.text_field :bank_account_type_code
  hr
  .row
    .three.columns
      = f.label :financial_insitution_number
      = f.text_field :financial_insitution_number
    .three.columns
      = f.label :branch_transit_number
      = f.text_field :branch_transit_number
    .three.columns
      = f.label :account_number
      = f.text_field :account_number
  hr
  .row
    .actions = f.submit

app/views/bank_accounts/edit.html.slim
h1 Editing bank_account

== render 'form'

= link_to 'Show', @bank_account
'|
= link_to 'Back', bank_accounts_path

app/views/bank_accounts/index.html.slim
h1 Listing bank_accounts

table
  thead
    tr
      th Bank account
      th Bank account name
      th Bank account owner
      th Bank account type code
      th Financial insitution number
      th Branch transit number
      th Account number
      th
      th
      th

  tbody
    - @bank_accounts.each do |bank_account|
      tr
        td = bank_account.bank_account_id
        td = bank_account.bank_account_name
        td = bank_account.bank_account_owner
        td = bank_account.bank_account_type_code
        td = bank_account.financial_insitution_number
        td = bank_account.branch_transit_number
        td = bank_account.account_number
        td = link_to 'Show', bank_account
        td = link_to 'Edit', edit_bank_account_path(bank_account)
        td = link_to 'Destroy', bank_account, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Bank account', new_bank_account_path, class: 'button button-primary'

app/views/bank_accounts/new.html.slim
h1 New bank_account

== render 'form'

= link_to 'Back', bank_accounts_path

app/views/bank_accounts/show.html.slim
pre#notice = notice

p
  strong Peloton Assigned Bank Account ID:
  = @bank_account.bank_account_id || 'nil'
p
  strong Bank account name:
  = @bank_account.bank_account_name
p
  strong Bank account owner:
  = @bank_account.bank_account_owner
p
  strong Bank account type code:
  = @bank_account.bank_account_type_code
p
  strong Financial insitution number:
  = @bank_account.financial_insitution_number
p
  strong Branch transit number:
  = @bank_account.branch_transit_number
p
  strong Account number:
  = @bank_account.account_number

hr
h3 Peloton Operations
.row
  .three.columns
    = form_for @bank_account, method: :put do |f|
      = f.hidden_field :add_bank_account, value: true
      = f.submit "Add Bank Account"
  .three.columns
    = form_for @bank_account, method: :put do |f|
      = f.text_field :amount, value: 10.10
      = f.hidden_field :deposit_funds, value: true
      = f.submit "Deposit Funds"
  .three.columns
    = form_for @bank_account, method: :put do |f|
      = f.hidden_field :delete_bank_account, value: true
      = f.submit "Delete Bank Account"
hr

= link_to 'Edit', edit_bank_account_path(@bank_account)
'|
= link_to 'Back', bank_accounts_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title DemoApp
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      .row
        header
          h1
            a[href="/"] DemoApp
      .row
        = yield